sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t aarjavdixit1/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true aarjavdixit1/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "Docker-React-v2"
  env: "DockerReactV2-env"
  bucket_name: "elasticbeanstalk-us-west-2-224077385082"
  bucket_path: "Docker-React-v2"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY